#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madden
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Madden")]
	public partial class MaddenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLeague(League instance);
    partial void UpdateLeague(League instance);
    partial void DeleteLeague(League instance);
    partial void InsertTeam(Team instance);
    partial void UpdateTeam(Team instance);
    partial void DeleteTeam(Team instance);
    partial void InsertPlayer(Player instance);
    partial void UpdatePlayer(Player instance);
    partial void DeletePlayer(Player instance);
    #endregion
		
		public MaddenDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MaddenConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MaddenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaddenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaddenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaddenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<League> Leagues
		{
			get
			{
				return this.GetTable<League>();
			}
		}
		
		public System.Data.Linq.Table<Team> Teams
		{
			get
			{
				return this.GetTable<Team>();
			}
		}
		
		public System.Data.Linq.Table<Player> Players
		{
			get
			{
				return this.GetTable<Player>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leagues")]
	public partial class League : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public League()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teams")]
	public partial class Team : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _LeagueID;
		
		private int _TeamId;
		
		private string _Username;
		
		private int _CurrentYear;
		
		private int _CurrentWeek;
		
		private string _City;
		
		private string _Name;
		
		private string _Conference;
		
		private string _Division;
		
		private int _OverallRating;
		
		private long _SalaryCapLimit;
		
		private long _SalaryCapSpent;
		
		private long _SalaryCapAvailable;
		
		private int _Wins;
		
		private int _Losses;
		
		private int _Ties;
		
		private int _PointsFor;
		
		private int _PointsAgainst;
		
		private int _NetPoints;
		
		private int _OFF_TotalYards;
		
		private int _OFF_RushYards;
		
		private int _OFF_PassYards;
		
		private int _DEF_TotalYards;
		
		private int _DEF_RushYards;
		
		private int _DEF_PashYards;
		
		private int _TurnoverDifferential;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLeagueIDChanging(int value);
    partial void OnLeagueIDChanged();
    partial void OnTeamIdChanging(int value);
    partial void OnTeamIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnCurrentYearChanging(int value);
    partial void OnCurrentYearChanged();
    partial void OnCurrentWeekChanging(int value);
    partial void OnCurrentWeekChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnConferenceChanging(string value);
    partial void OnConferenceChanged();
    partial void OnDivisionChanging(string value);
    partial void OnDivisionChanged();
    partial void OnOverallRatingChanging(int value);
    partial void OnOverallRatingChanged();
    partial void OnSalaryCapLimitChanging(long value);
    partial void OnSalaryCapLimitChanged();
    partial void OnSalaryCapSpentChanging(long value);
    partial void OnSalaryCapSpentChanged();
    partial void OnSalaryCapAvailableChanging(long value);
    partial void OnSalaryCapAvailableChanged();
    partial void OnWinsChanging(int value);
    partial void OnWinsChanged();
    partial void OnLossesChanging(int value);
    partial void OnLossesChanged();
    partial void OnTiesChanging(int value);
    partial void OnTiesChanged();
    partial void OnPointsForChanging(int value);
    partial void OnPointsForChanged();
    partial void OnPointsAgainstChanging(int value);
    partial void OnPointsAgainstChanged();
    partial void OnNetPointsChanging(int value);
    partial void OnNetPointsChanged();
    partial void OnOFF_TotalYardsChanging(int value);
    partial void OnOFF_TotalYardsChanged();
    partial void OnOFF_RushYardsChanging(int value);
    partial void OnOFF_RushYardsChanged();
    partial void OnOFF_PassYardsChanging(int value);
    partial void OnOFF_PassYardsChanged();
    partial void OnDEF_TotalYardsChanging(int value);
    partial void OnDEF_TotalYardsChanged();
    partial void OnDEF_RushYardsChanging(int value);
    partial void OnDEF_RushYardsChanged();
    partial void OnDEF_PashYardsChanging(int value);
    partial void OnDEF_PashYardsChanged();
    partial void OnTurnoverDifferentialChanging(int value);
    partial void OnTurnoverDifferentialChanged();
    #endregion
		
		public Team()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeagueID", DbType="Int NOT NULL")]
		public int LeagueID
		{
			get
			{
				return this._LeagueID;
			}
			set
			{
				if ((this._LeagueID != value))
				{
					this.OnLeagueIDChanging(value);
					this.SendPropertyChanging();
					this._LeagueID = value;
					this.SendPropertyChanged("LeagueID");
					this.OnLeagueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamId", DbType="Int NOT NULL")]
		public int TeamId
		{
			get
			{
				return this._TeamId;
			}
			set
			{
				if ((this._TeamId != value))
				{
					this.OnTeamIdChanging(value);
					this.SendPropertyChanging();
					this._TeamId = value;
					this.SendPropertyChanged("TeamId");
					this.OnTeamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(MAX)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentYear", DbType="Int NOT NULL")]
		public int CurrentYear
		{
			get
			{
				return this._CurrentYear;
			}
			set
			{
				if ((this._CurrentYear != value))
				{
					this.OnCurrentYearChanging(value);
					this.SendPropertyChanging();
					this._CurrentYear = value;
					this.SendPropertyChanged("CurrentYear");
					this.OnCurrentYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentWeek", DbType="Int NOT NULL")]
		public int CurrentWeek
		{
			get
			{
				return this._CurrentWeek;
			}
			set
			{
				if ((this._CurrentWeek != value))
				{
					this.OnCurrentWeekChanging(value);
					this.SendPropertyChanging();
					this._CurrentWeek = value;
					this.SendPropertyChanged("CurrentWeek");
					this.OnCurrentWeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conference", DbType="NVarChar(MAX)")]
		public string Conference
		{
			get
			{
				return this._Conference;
			}
			set
			{
				if ((this._Conference != value))
				{
					this.OnConferenceChanging(value);
					this.SendPropertyChanging();
					this._Conference = value;
					this.SendPropertyChanged("Conference");
					this.OnConferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NVarChar(MAX)")]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverallRating", DbType="Int NOT NULL")]
		public int OverallRating
		{
			get
			{
				return this._OverallRating;
			}
			set
			{
				if ((this._OverallRating != value))
				{
					this.OnOverallRatingChanging(value);
					this.SendPropertyChanging();
					this._OverallRating = value;
					this.SendPropertyChanged("OverallRating");
					this.OnOverallRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryCapLimit", DbType="BigInt NOT NULL")]
		public long SalaryCapLimit
		{
			get
			{
				return this._SalaryCapLimit;
			}
			set
			{
				if ((this._SalaryCapLimit != value))
				{
					this.OnSalaryCapLimitChanging(value);
					this.SendPropertyChanging();
					this._SalaryCapLimit = value;
					this.SendPropertyChanged("SalaryCapLimit");
					this.OnSalaryCapLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryCapSpent", DbType="BigInt NOT NULL")]
		public long SalaryCapSpent
		{
			get
			{
				return this._SalaryCapSpent;
			}
			set
			{
				if ((this._SalaryCapSpent != value))
				{
					this.OnSalaryCapSpentChanging(value);
					this.SendPropertyChanging();
					this._SalaryCapSpent = value;
					this.SendPropertyChanged("SalaryCapSpent");
					this.OnSalaryCapSpentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryCapAvailable", DbType="BigInt NOT NULL")]
		public long SalaryCapAvailable
		{
			get
			{
				return this._SalaryCapAvailable;
			}
			set
			{
				if ((this._SalaryCapAvailable != value))
				{
					this.OnSalaryCapAvailableChanging(value);
					this.SendPropertyChanging();
					this._SalaryCapAvailable = value;
					this.SendPropertyChanged("SalaryCapAvailable");
					this.OnSalaryCapAvailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wins", DbType="Int NOT NULL")]
		public int Wins
		{
			get
			{
				return this._Wins;
			}
			set
			{
				if ((this._Wins != value))
				{
					this.OnWinsChanging(value);
					this.SendPropertyChanging();
					this._Wins = value;
					this.SendPropertyChanged("Wins");
					this.OnWinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Losses", DbType="Int NOT NULL")]
		public int Losses
		{
			get
			{
				return this._Losses;
			}
			set
			{
				if ((this._Losses != value))
				{
					this.OnLossesChanging(value);
					this.SendPropertyChanging();
					this._Losses = value;
					this.SendPropertyChanged("Losses");
					this.OnLossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ties", DbType="Int NOT NULL")]
		public int Ties
		{
			get
			{
				return this._Ties;
			}
			set
			{
				if ((this._Ties != value))
				{
					this.OnTiesChanging(value);
					this.SendPropertyChanging();
					this._Ties = value;
					this.SendPropertyChanged("Ties");
					this.OnTiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsFor", DbType="Int NOT NULL")]
		public int PointsFor
		{
			get
			{
				return this._PointsFor;
			}
			set
			{
				if ((this._PointsFor != value))
				{
					this.OnPointsForChanging(value);
					this.SendPropertyChanging();
					this._PointsFor = value;
					this.SendPropertyChanged("PointsFor");
					this.OnPointsForChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsAgainst", DbType="Int NOT NULL")]
		public int PointsAgainst
		{
			get
			{
				return this._PointsAgainst;
			}
			set
			{
				if ((this._PointsAgainst != value))
				{
					this.OnPointsAgainstChanging(value);
					this.SendPropertyChanging();
					this._PointsAgainst = value;
					this.SendPropertyChanged("PointsAgainst");
					this.OnPointsAgainstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetPoints", DbType="Int NOT NULL")]
		public int NetPoints
		{
			get
			{
				return this._NetPoints;
			}
			set
			{
				if ((this._NetPoints != value))
				{
					this.OnNetPointsChanging(value);
					this.SendPropertyChanging();
					this._NetPoints = value;
					this.SendPropertyChanged("NetPoints");
					this.OnNetPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFF_TotalYards", DbType="Int NOT NULL")]
		public int OFF_TotalYards
		{
			get
			{
				return this._OFF_TotalYards;
			}
			set
			{
				if ((this._OFF_TotalYards != value))
				{
					this.OnOFF_TotalYardsChanging(value);
					this.SendPropertyChanging();
					this._OFF_TotalYards = value;
					this.SendPropertyChanged("OFF_TotalYards");
					this.OnOFF_TotalYardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFF_RushYards", DbType="Int NOT NULL")]
		public int OFF_RushYards
		{
			get
			{
				return this._OFF_RushYards;
			}
			set
			{
				if ((this._OFF_RushYards != value))
				{
					this.OnOFF_RushYardsChanging(value);
					this.SendPropertyChanging();
					this._OFF_RushYards = value;
					this.SendPropertyChanged("OFF_RushYards");
					this.OnOFF_RushYardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFF_PassYards", DbType="Int NOT NULL")]
		public int OFF_PassYards
		{
			get
			{
				return this._OFF_PassYards;
			}
			set
			{
				if ((this._OFF_PassYards != value))
				{
					this.OnOFF_PassYardsChanging(value);
					this.SendPropertyChanging();
					this._OFF_PassYards = value;
					this.SendPropertyChanged("OFF_PassYards");
					this.OnOFF_PassYardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEF_TotalYards", DbType="Int NOT NULL")]
		public int DEF_TotalYards
		{
			get
			{
				return this._DEF_TotalYards;
			}
			set
			{
				if ((this._DEF_TotalYards != value))
				{
					this.OnDEF_TotalYardsChanging(value);
					this.SendPropertyChanging();
					this._DEF_TotalYards = value;
					this.SendPropertyChanged("DEF_TotalYards");
					this.OnDEF_TotalYardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEF_RushYards", DbType="Int NOT NULL")]
		public int DEF_RushYards
		{
			get
			{
				return this._DEF_RushYards;
			}
			set
			{
				if ((this._DEF_RushYards != value))
				{
					this.OnDEF_RushYardsChanging(value);
					this.SendPropertyChanging();
					this._DEF_RushYards = value;
					this.SendPropertyChanged("DEF_RushYards");
					this.OnDEF_RushYardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEF_PashYards", DbType="Int NOT NULL")]
		public int DEF_PashYards
		{
			get
			{
				return this._DEF_PashYards;
			}
			set
			{
				if ((this._DEF_PashYards != value))
				{
					this.OnDEF_PashYardsChanging(value);
					this.SendPropertyChanging();
					this._DEF_PashYards = value;
					this.SendPropertyChanged("DEF_PashYards");
					this.OnDEF_PashYardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurnoverDifferential", DbType="Int NOT NULL")]
		public int TurnoverDifferential
		{
			get
			{
				return this._TurnoverDifferential;
			}
			set
			{
				if ((this._TurnoverDifferential != value))
				{
					this.OnTurnoverDifferentialChanging(value);
					this.SendPropertyChanging();
					this._TurnoverDifferential = value;
					this.SendPropertyChanged("TurnoverDifferential");
					this.OnTurnoverDifferentialChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Players")]
	public partial class Player : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _LeagueID;
		
		private int _PlayerId;
		
		private string _Position;
		
		private string _FirstName;
		
		private string _LastName;
		
		private int _Age;
		
		private int _Height;
		
		private int _Weight;
		
		private int _Overall;
		
		private int _XP;
		
		private int _Number;
		
		private int _YearsPro;
		
		private int _TeamId;
		
		private int _Development;
		
		private bool _IsFreeAgent;
		
		private int _Scheme;
		
		private int _Confidence;
		
		private long _ContractSalary;
		
		private long _ContractBonus;
		
		private int _ContractLength;
		
		private int _ContractYearsLeft;
		
		private long _ContractCapHit;
		
		private long _ContractReleasePenalty;
		
		private long _ContractReleaseNetSavings;
		
		private int _Awareness;
		
		private int _Speed;
		
		private int _Acceleration;
		
		private int _Agility;
		
		private int _Strength;
		
		private int _Catch;
		
		private int _Jump;
		
		private int _KickReturn;
		
		private int _Stamina;
		
		private int _Injury;
		
		private int _Toughness;
		
		private int _Durability;
		
		private int _Elusiveness;
		
		private int _Carry;
		
		private int _ThrowPower;
		
		private int _ThrowAccuracy;
		
		private int _ThrowAccuracyShort;
		
		private int _ThrowAccuracyMid;
		
		private int _ThrowAccuracyDeep;
		
		private int _ThrowOnRun;
		
		private int _PlayAction;
		
		private int _BallCarrierVision;
		
		private int _Trucking;
		
		private int _JukeMove;
		
		private int _SpinMove;
		
		private int _StiffArm;
		
		private int _Release;
		
		private int _RouteRunning;
		
		private int _CatchInTraffic;
		
		private int _SpectacularCatch;
		
		private int _RunBlock;
		
		private int _PassBlock;
		
		private int _ImpactBlock;
		
		private int _Tackle;
		
		private int _HitPower;
		
		private int _PlayRecognition;
		
		private int _Pursuit;
		
		private int _BlockShed;
		
		private int _PowerMoves;
		
		private int _FinesseMoves;
		
		private int _ManCover;
		
		private int _ZoneCover;
		
		private int _PressCover;
		
		private int _KickPower;
		
		private int _KickAccuracy;
		
		private int _Trait_ALL_Predictable;
		
		private int _Trait_ALL_Clutch;
		
		private int _Trait_ALL_Penalty;
		
		private int _Trait_OFF_CoverBall;
		
		private int _Trait_OFF_FightForYards;
		
		private int _Trait_OFF_DropOpenPasses;
		
		private int _Trait_OFF_FeetInBounds;
		
		private int _Trait_OFF_PossesionCatch;
		
		private int _Trait_OFF_AggressiveCatch;
		
		private int _Trait_OFF_CatchOnTheRun;
		
		private int _Trait_QB_ThrowBallAway;
		
		private int _Trait_QB_SensePressure;
		
		private int _Trait_QB_TightSpiral;
		
		private int _Trait_QB_Style;
		
		private int _Trait_QB_ForcePass;
		
		private int _Trait_DEF_BullRush;
		
		private int _Trait_DEF_SwimMove;
		
		private int _Trait_DEF_SpinMove;
		
		private int _Trait_DEF_HighMotor;
		
		private int _Trait_DEF_BigHitter;
		
		private int _Trait_DEF_StripBall;
		
		private int _Trait_DEF_PlayBall;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLeagueIDChanging(int value);
    partial void OnLeagueIDChanged();
    partial void OnPlayerIdChanging(int value);
    partial void OnPlayerIdChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnAgeChanging(int value);
    partial void OnAgeChanged();
    partial void OnHeightChanging(int value);
    partial void OnHeightChanged();
    partial void OnWeightChanging(int value);
    partial void OnWeightChanged();
    partial void OnOverallChanging(int value);
    partial void OnOverallChanged();
    partial void OnXPChanging(int value);
    partial void OnXPChanged();
    partial void OnNumberChanging(int value);
    partial void OnNumberChanged();
    partial void OnYearsProChanging(int value);
    partial void OnYearsProChanged();
    partial void OnTeamIdChanging(int value);
    partial void OnTeamIdChanged();
    partial void OnDevelopmentChanging(int value);
    partial void OnDevelopmentChanged();
    partial void OnIsFreeAgentChanging(bool value);
    partial void OnIsFreeAgentChanged();
    partial void OnSchemeChanging(int value);
    partial void OnSchemeChanged();
    partial void OnConfidenceChanging(int value);
    partial void OnConfidenceChanged();
    partial void OnContractSalaryChanging(long value);
    partial void OnContractSalaryChanged();
    partial void OnContractBonusChanging(long value);
    partial void OnContractBonusChanged();
    partial void OnContractLengthChanging(int value);
    partial void OnContractLengthChanged();
    partial void OnContractYearsLeftChanging(int value);
    partial void OnContractYearsLeftChanged();
    partial void OnContractCapHitChanging(long value);
    partial void OnContractCapHitChanged();
    partial void OnContractReleasePenaltyChanging(long value);
    partial void OnContractReleasePenaltyChanged();
    partial void OnContractReleaseNetSavingsChanging(long value);
    partial void OnContractReleaseNetSavingsChanged();
    partial void OnAwarenessChanging(int value);
    partial void OnAwarenessChanged();
    partial void OnSpeedChanging(int value);
    partial void OnSpeedChanged();
    partial void OnAccelerationChanging(int value);
    partial void OnAccelerationChanged();
    partial void OnAgilityChanging(int value);
    partial void OnAgilityChanged();
    partial void OnStrengthChanging(int value);
    partial void OnStrengthChanged();
    partial void OnCatchChanging(int value);
    partial void OnCatchChanged();
    partial void OnJumpChanging(int value);
    partial void OnJumpChanged();
    partial void OnKickReturnChanging(int value);
    partial void OnKickReturnChanged();
    partial void OnStaminaChanging(int value);
    partial void OnStaminaChanged();
    partial void OnInjuryChanging(int value);
    partial void OnInjuryChanged();
    partial void OnToughnessChanging(int value);
    partial void OnToughnessChanged();
    partial void OnDurabilityChanging(int value);
    partial void OnDurabilityChanged();
    partial void OnElusivenessChanging(int value);
    partial void OnElusivenessChanged();
    partial void OnCarryChanging(int value);
    partial void OnCarryChanged();
    partial void OnThrowPowerChanging(int value);
    partial void OnThrowPowerChanged();
    partial void OnThrowAccuracyChanging(int value);
    partial void OnThrowAccuracyChanged();
    partial void OnThrowAccuracyShortChanging(int value);
    partial void OnThrowAccuracyShortChanged();
    partial void OnThrowAccuracyMidChanging(int value);
    partial void OnThrowAccuracyMidChanged();
    partial void OnThrowAccuracyDeepChanging(int value);
    partial void OnThrowAccuracyDeepChanged();
    partial void OnThrowOnRunChanging(int value);
    partial void OnThrowOnRunChanged();
    partial void OnPlayActionChanging(int value);
    partial void OnPlayActionChanged();
    partial void OnBallCarrierVisionChanging(int value);
    partial void OnBallCarrierVisionChanged();
    partial void OnTruckingChanging(int value);
    partial void OnTruckingChanged();
    partial void OnJukeMoveChanging(int value);
    partial void OnJukeMoveChanged();
    partial void OnSpinMoveChanging(int value);
    partial void OnSpinMoveChanged();
    partial void OnStiffArmChanging(int value);
    partial void OnStiffArmChanged();
    partial void OnReleaseChanging(int value);
    partial void OnReleaseChanged();
    partial void OnRouteRunningChanging(int value);
    partial void OnRouteRunningChanged();
    partial void OnCatchInTrafficChanging(int value);
    partial void OnCatchInTrafficChanged();
    partial void OnSpectacularCatchChanging(int value);
    partial void OnSpectacularCatchChanged();
    partial void OnRunBlockChanging(int value);
    partial void OnRunBlockChanged();
    partial void OnPassBlockChanging(int value);
    partial void OnPassBlockChanged();
    partial void OnImpactBlockChanging(int value);
    partial void OnImpactBlockChanged();
    partial void OnTackleChanging(int value);
    partial void OnTackleChanged();
    partial void OnHitPowerChanging(int value);
    partial void OnHitPowerChanged();
    partial void OnPlayRecognitionChanging(int value);
    partial void OnPlayRecognitionChanged();
    partial void OnPursuitChanging(int value);
    partial void OnPursuitChanged();
    partial void OnBlockShedChanging(int value);
    partial void OnBlockShedChanged();
    partial void OnPowerMovesChanging(int value);
    partial void OnPowerMovesChanged();
    partial void OnFinesseMovesChanging(int value);
    partial void OnFinesseMovesChanged();
    partial void OnManCoverChanging(int value);
    partial void OnManCoverChanged();
    partial void OnZoneCoverChanging(int value);
    partial void OnZoneCoverChanged();
    partial void OnPressCoverChanging(int value);
    partial void OnPressCoverChanged();
    partial void OnKickPowerChanging(int value);
    partial void OnKickPowerChanged();
    partial void OnKickAccuracyChanging(int value);
    partial void OnKickAccuracyChanged();
    partial void OnTrait_ALL_PredictableChanging(int value);
    partial void OnTrait_ALL_PredictableChanged();
    partial void OnTrait_ALL_ClutchChanging(int value);
    partial void OnTrait_ALL_ClutchChanged();
    partial void OnTrait_ALL_PenaltyChanging(int value);
    partial void OnTrait_ALL_PenaltyChanged();
    partial void OnTrait_OFF_CoverBallChanging(int value);
    partial void OnTrait_OFF_CoverBallChanged();
    partial void OnTrait_OFF_FightForYardsChanging(int value);
    partial void OnTrait_OFF_FightForYardsChanged();
    partial void OnTrait_OFF_DropOpenPassesChanging(int value);
    partial void OnTrait_OFF_DropOpenPassesChanged();
    partial void OnTrait_OFF_FeetInBoundsChanging(int value);
    partial void OnTrait_OFF_FeetInBoundsChanged();
    partial void OnTrait_OFF_PossesionCatchChanging(int value);
    partial void OnTrait_OFF_PossesionCatchChanged();
    partial void OnTrait_OFF_AggressiveCatchChanging(int value);
    partial void OnTrait_OFF_AggressiveCatchChanged();
    partial void OnTrait_OFF_CatchOnTheRunChanging(int value);
    partial void OnTrait_OFF_CatchOnTheRunChanged();
    partial void OnTrait_QB_ThrowBallAwayChanging(int value);
    partial void OnTrait_QB_ThrowBallAwayChanged();
    partial void OnTrait_QB_SensePressureChanging(int value);
    partial void OnTrait_QB_SensePressureChanged();
    partial void OnTrait_QB_TightSpiralChanging(int value);
    partial void OnTrait_QB_TightSpiralChanged();
    partial void OnTrait_QB_StyleChanging(int value);
    partial void OnTrait_QB_StyleChanged();
    partial void OnTrait_QB_ForcePassChanging(int value);
    partial void OnTrait_QB_ForcePassChanged();
    partial void OnTrait_DEF_BullRushChanging(int value);
    partial void OnTrait_DEF_BullRushChanged();
    partial void OnTrait_DEF_SwimMoveChanging(int value);
    partial void OnTrait_DEF_SwimMoveChanged();
    partial void OnTrait_DEF_SpinMoveChanging(int value);
    partial void OnTrait_DEF_SpinMoveChanged();
    partial void OnTrait_DEF_HighMotorChanging(int value);
    partial void OnTrait_DEF_HighMotorChanged();
    partial void OnTrait_DEF_BigHitterChanging(int value);
    partial void OnTrait_DEF_BigHitterChanged();
    partial void OnTrait_DEF_StripBallChanging(int value);
    partial void OnTrait_DEF_StripBallChanged();
    partial void OnTrait_DEF_PlayBallChanging(int value);
    partial void OnTrait_DEF_PlayBallChanged();
    #endregion
		
		public Player()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeagueID", DbType="Int NOT NULL")]
		public int LeagueID
		{
			get
			{
				return this._LeagueID;
			}
			set
			{
				if ((this._LeagueID != value))
				{
					this.OnLeagueIDChanging(value);
					this.SendPropertyChanging();
					this._LeagueID = value;
					this.SendPropertyChanged("LeagueID");
					this.OnLeagueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayerId", DbType="Int NOT NULL")]
		public int PlayerId
		{
			get
			{
				return this._PlayerId;
			}
			set
			{
				if ((this._PlayerId != value))
				{
					this.OnPlayerIdChanging(value);
					this.SendPropertyChanging();
					this._PlayerId = value;
					this.SendPropertyChanged("PlayerId");
					this.OnPlayerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int NOT NULL")]
		public int Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Int NOT NULL")]
		public int Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int NOT NULL")]
		public int Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Overall", DbType="Int NOT NULL")]
		public int Overall
		{
			get
			{
				return this._Overall;
			}
			set
			{
				if ((this._Overall != value))
				{
					this.OnOverallChanging(value);
					this.SendPropertyChanging();
					this._Overall = value;
					this.SendPropertyChanged("Overall");
					this.OnOverallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XP", DbType="Int NOT NULL")]
		public int XP
		{
			get
			{
				return this._XP;
			}
			set
			{
				if ((this._XP != value))
				{
					this.OnXPChanging(value);
					this.SendPropertyChanging();
					this._XP = value;
					this.SendPropertyChanged("XP");
					this.OnXPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsPro", DbType="Int NOT NULL")]
		public int YearsPro
		{
			get
			{
				return this._YearsPro;
			}
			set
			{
				if ((this._YearsPro != value))
				{
					this.OnYearsProChanging(value);
					this.SendPropertyChanging();
					this._YearsPro = value;
					this.SendPropertyChanged("YearsPro");
					this.OnYearsProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamId", DbType="Int NOT NULL")]
		public int TeamId
		{
			get
			{
				return this._TeamId;
			}
			set
			{
				if ((this._TeamId != value))
				{
					this.OnTeamIdChanging(value);
					this.SendPropertyChanging();
					this._TeamId = value;
					this.SendPropertyChanged("TeamId");
					this.OnTeamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Development", DbType="Int NOT NULL")]
		public int Development
		{
			get
			{
				return this._Development;
			}
			set
			{
				if ((this._Development != value))
				{
					this.OnDevelopmentChanging(value);
					this.SendPropertyChanging();
					this._Development = value;
					this.SendPropertyChanged("Development");
					this.OnDevelopmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFreeAgent", DbType="Bit NOT NULL")]
		public bool IsFreeAgent
		{
			get
			{
				return this._IsFreeAgent;
			}
			set
			{
				if ((this._IsFreeAgent != value))
				{
					this.OnIsFreeAgentChanging(value);
					this.SendPropertyChanging();
					this._IsFreeAgent = value;
					this.SendPropertyChanged("IsFreeAgent");
					this.OnIsFreeAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scheme", DbType="Int NOT NULL")]
		public int Scheme
		{
			get
			{
				return this._Scheme;
			}
			set
			{
				if ((this._Scheme != value))
				{
					this.OnSchemeChanging(value);
					this.SendPropertyChanging();
					this._Scheme = value;
					this.SendPropertyChanged("Scheme");
					this.OnSchemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confidence", DbType="Int NOT NULL")]
		public int Confidence
		{
			get
			{
				return this._Confidence;
			}
			set
			{
				if ((this._Confidence != value))
				{
					this.OnConfidenceChanging(value);
					this.SendPropertyChanging();
					this._Confidence = value;
					this.SendPropertyChanged("Confidence");
					this.OnConfidenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractSalary", DbType="BigInt NOT NULL")]
		public long ContractSalary
		{
			get
			{
				return this._ContractSalary;
			}
			set
			{
				if ((this._ContractSalary != value))
				{
					this.OnContractSalaryChanging(value);
					this.SendPropertyChanging();
					this._ContractSalary = value;
					this.SendPropertyChanged("ContractSalary");
					this.OnContractSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractBonus", DbType="BigInt NOT NULL")]
		public long ContractBonus
		{
			get
			{
				return this._ContractBonus;
			}
			set
			{
				if ((this._ContractBonus != value))
				{
					this.OnContractBonusChanging(value);
					this.SendPropertyChanging();
					this._ContractBonus = value;
					this.SendPropertyChanged("ContractBonus");
					this.OnContractBonusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractLength", DbType="Int NOT NULL")]
		public int ContractLength
		{
			get
			{
				return this._ContractLength;
			}
			set
			{
				if ((this._ContractLength != value))
				{
					this.OnContractLengthChanging(value);
					this.SendPropertyChanging();
					this._ContractLength = value;
					this.SendPropertyChanged("ContractLength");
					this.OnContractLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractYearsLeft", DbType="Int NOT NULL")]
		public int ContractYearsLeft
		{
			get
			{
				return this._ContractYearsLeft;
			}
			set
			{
				if ((this._ContractYearsLeft != value))
				{
					this.OnContractYearsLeftChanging(value);
					this.SendPropertyChanging();
					this._ContractYearsLeft = value;
					this.SendPropertyChanged("ContractYearsLeft");
					this.OnContractYearsLeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractCapHit", DbType="BigInt NOT NULL")]
		public long ContractCapHit
		{
			get
			{
				return this._ContractCapHit;
			}
			set
			{
				if ((this._ContractCapHit != value))
				{
					this.OnContractCapHitChanging(value);
					this.SendPropertyChanging();
					this._ContractCapHit = value;
					this.SendPropertyChanged("ContractCapHit");
					this.OnContractCapHitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractReleasePenalty", DbType="BigInt NOT NULL")]
		public long ContractReleasePenalty
		{
			get
			{
				return this._ContractReleasePenalty;
			}
			set
			{
				if ((this._ContractReleasePenalty != value))
				{
					this.OnContractReleasePenaltyChanging(value);
					this.SendPropertyChanging();
					this._ContractReleasePenalty = value;
					this.SendPropertyChanged("ContractReleasePenalty");
					this.OnContractReleasePenaltyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractReleaseNetSavings", DbType="BigInt NOT NULL")]
		public long ContractReleaseNetSavings
		{
			get
			{
				return this._ContractReleaseNetSavings;
			}
			set
			{
				if ((this._ContractReleaseNetSavings != value))
				{
					this.OnContractReleaseNetSavingsChanging(value);
					this.SendPropertyChanging();
					this._ContractReleaseNetSavings = value;
					this.SendPropertyChanged("ContractReleaseNetSavings");
					this.OnContractReleaseNetSavingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Awareness", DbType="Int NOT NULL")]
		public int Awareness
		{
			get
			{
				return this._Awareness;
			}
			set
			{
				if ((this._Awareness != value))
				{
					this.OnAwarenessChanging(value);
					this.SendPropertyChanging();
					this._Awareness = value;
					this.SendPropertyChanged("Awareness");
					this.OnAwarenessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="Int NOT NULL")]
		public int Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this.OnSpeedChanging(value);
					this.SendPropertyChanging();
					this._Speed = value;
					this.SendPropertyChanged("Speed");
					this.OnSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acceleration", DbType="Int NOT NULL")]
		public int Acceleration
		{
			get
			{
				return this._Acceleration;
			}
			set
			{
				if ((this._Acceleration != value))
				{
					this.OnAccelerationChanging(value);
					this.SendPropertyChanging();
					this._Acceleration = value;
					this.SendPropertyChanged("Acceleration");
					this.OnAccelerationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agility", DbType="Int NOT NULL")]
		public int Agility
		{
			get
			{
				return this._Agility;
			}
			set
			{
				if ((this._Agility != value))
				{
					this.OnAgilityChanging(value);
					this.SendPropertyChanging();
					this._Agility = value;
					this.SendPropertyChanged("Agility");
					this.OnAgilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Strength", DbType="Int NOT NULL")]
		public int Strength
		{
			get
			{
				return this._Strength;
			}
			set
			{
				if ((this._Strength != value))
				{
					this.OnStrengthChanging(value);
					this.SendPropertyChanging();
					this._Strength = value;
					this.SendPropertyChanged("Strength");
					this.OnStrengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catch", DbType="Int NOT NULL")]
		public int Catch
		{
			get
			{
				return this._Catch;
			}
			set
			{
				if ((this._Catch != value))
				{
					this.OnCatchChanging(value);
					this.SendPropertyChanging();
					this._Catch = value;
					this.SendPropertyChanged("Catch");
					this.OnCatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jump", DbType="Int NOT NULL")]
		public int Jump
		{
			get
			{
				return this._Jump;
			}
			set
			{
				if ((this._Jump != value))
				{
					this.OnJumpChanging(value);
					this.SendPropertyChanging();
					this._Jump = value;
					this.SendPropertyChanged("Jump");
					this.OnJumpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KickReturn", DbType="Int NOT NULL")]
		public int KickReturn
		{
			get
			{
				return this._KickReturn;
			}
			set
			{
				if ((this._KickReturn != value))
				{
					this.OnKickReturnChanging(value);
					this.SendPropertyChanging();
					this._KickReturn = value;
					this.SendPropertyChanged("KickReturn");
					this.OnKickReturnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stamina", DbType="Int NOT NULL")]
		public int Stamina
		{
			get
			{
				return this._Stamina;
			}
			set
			{
				if ((this._Stamina != value))
				{
					this.OnStaminaChanging(value);
					this.SendPropertyChanging();
					this._Stamina = value;
					this.SendPropertyChanged("Stamina");
					this.OnStaminaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Injury", DbType="Int NOT NULL")]
		public int Injury
		{
			get
			{
				return this._Injury;
			}
			set
			{
				if ((this._Injury != value))
				{
					this.OnInjuryChanging(value);
					this.SendPropertyChanging();
					this._Injury = value;
					this.SendPropertyChanged("Injury");
					this.OnInjuryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Toughness", DbType="Int NOT NULL")]
		public int Toughness
		{
			get
			{
				return this._Toughness;
			}
			set
			{
				if ((this._Toughness != value))
				{
					this.OnToughnessChanging(value);
					this.SendPropertyChanging();
					this._Toughness = value;
					this.SendPropertyChanged("Toughness");
					this.OnToughnessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durability", DbType="Int NOT NULL")]
		public int Durability
		{
			get
			{
				return this._Durability;
			}
			set
			{
				if ((this._Durability != value))
				{
					this.OnDurabilityChanging(value);
					this.SendPropertyChanging();
					this._Durability = value;
					this.SendPropertyChanged("Durability");
					this.OnDurabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Elusiveness", DbType="Int NOT NULL")]
		public int Elusiveness
		{
			get
			{
				return this._Elusiveness;
			}
			set
			{
				if ((this._Elusiveness != value))
				{
					this.OnElusivenessChanging(value);
					this.SendPropertyChanging();
					this._Elusiveness = value;
					this.SendPropertyChanged("Elusiveness");
					this.OnElusivenessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carry", DbType="Int NOT NULL")]
		public int Carry
		{
			get
			{
				return this._Carry;
			}
			set
			{
				if ((this._Carry != value))
				{
					this.OnCarryChanging(value);
					this.SendPropertyChanging();
					this._Carry = value;
					this.SendPropertyChanged("Carry");
					this.OnCarryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThrowPower", DbType="Int NOT NULL")]
		public int ThrowPower
		{
			get
			{
				return this._ThrowPower;
			}
			set
			{
				if ((this._ThrowPower != value))
				{
					this.OnThrowPowerChanging(value);
					this.SendPropertyChanging();
					this._ThrowPower = value;
					this.SendPropertyChanged("ThrowPower");
					this.OnThrowPowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThrowAccuracy", DbType="Int NOT NULL")]
		public int ThrowAccuracy
		{
			get
			{
				return this._ThrowAccuracy;
			}
			set
			{
				if ((this._ThrowAccuracy != value))
				{
					this.OnThrowAccuracyChanging(value);
					this.SendPropertyChanging();
					this._ThrowAccuracy = value;
					this.SendPropertyChanged("ThrowAccuracy");
					this.OnThrowAccuracyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThrowAccuracyShort", DbType="Int NOT NULL")]
		public int ThrowAccuracyShort
		{
			get
			{
				return this._ThrowAccuracyShort;
			}
			set
			{
				if ((this._ThrowAccuracyShort != value))
				{
					this.OnThrowAccuracyShortChanging(value);
					this.SendPropertyChanging();
					this._ThrowAccuracyShort = value;
					this.SendPropertyChanged("ThrowAccuracyShort");
					this.OnThrowAccuracyShortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThrowAccuracyMid", DbType="Int NOT NULL")]
		public int ThrowAccuracyMid
		{
			get
			{
				return this._ThrowAccuracyMid;
			}
			set
			{
				if ((this._ThrowAccuracyMid != value))
				{
					this.OnThrowAccuracyMidChanging(value);
					this.SendPropertyChanging();
					this._ThrowAccuracyMid = value;
					this.SendPropertyChanged("ThrowAccuracyMid");
					this.OnThrowAccuracyMidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThrowAccuracyDeep", DbType="Int NOT NULL")]
		public int ThrowAccuracyDeep
		{
			get
			{
				return this._ThrowAccuracyDeep;
			}
			set
			{
				if ((this._ThrowAccuracyDeep != value))
				{
					this.OnThrowAccuracyDeepChanging(value);
					this.SendPropertyChanging();
					this._ThrowAccuracyDeep = value;
					this.SendPropertyChanged("ThrowAccuracyDeep");
					this.OnThrowAccuracyDeepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThrowOnRun", DbType="Int NOT NULL")]
		public int ThrowOnRun
		{
			get
			{
				return this._ThrowOnRun;
			}
			set
			{
				if ((this._ThrowOnRun != value))
				{
					this.OnThrowOnRunChanging(value);
					this.SendPropertyChanging();
					this._ThrowOnRun = value;
					this.SendPropertyChanged("ThrowOnRun");
					this.OnThrowOnRunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayAction", DbType="Int NOT NULL")]
		public int PlayAction
		{
			get
			{
				return this._PlayAction;
			}
			set
			{
				if ((this._PlayAction != value))
				{
					this.OnPlayActionChanging(value);
					this.SendPropertyChanging();
					this._PlayAction = value;
					this.SendPropertyChanged("PlayAction");
					this.OnPlayActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BallCarrierVision", DbType="Int NOT NULL")]
		public int BallCarrierVision
		{
			get
			{
				return this._BallCarrierVision;
			}
			set
			{
				if ((this._BallCarrierVision != value))
				{
					this.OnBallCarrierVisionChanging(value);
					this.SendPropertyChanging();
					this._BallCarrierVision = value;
					this.SendPropertyChanged("BallCarrierVision");
					this.OnBallCarrierVisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trucking", DbType="Int NOT NULL")]
		public int Trucking
		{
			get
			{
				return this._Trucking;
			}
			set
			{
				if ((this._Trucking != value))
				{
					this.OnTruckingChanging(value);
					this.SendPropertyChanging();
					this._Trucking = value;
					this.SendPropertyChanged("Trucking");
					this.OnTruckingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JukeMove", DbType="Int NOT NULL")]
		public int JukeMove
		{
			get
			{
				return this._JukeMove;
			}
			set
			{
				if ((this._JukeMove != value))
				{
					this.OnJukeMoveChanging(value);
					this.SendPropertyChanging();
					this._JukeMove = value;
					this.SendPropertyChanged("JukeMove");
					this.OnJukeMoveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpinMove", DbType="Int NOT NULL")]
		public int SpinMove
		{
			get
			{
				return this._SpinMove;
			}
			set
			{
				if ((this._SpinMove != value))
				{
					this.OnSpinMoveChanging(value);
					this.SendPropertyChanging();
					this._SpinMove = value;
					this.SendPropertyChanged("SpinMove");
					this.OnSpinMoveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StiffArm", DbType="Int NOT NULL")]
		public int StiffArm
		{
			get
			{
				return this._StiffArm;
			}
			set
			{
				if ((this._StiffArm != value))
				{
					this.OnStiffArmChanging(value);
					this.SendPropertyChanging();
					this._StiffArm = value;
					this.SendPropertyChanged("StiffArm");
					this.OnStiffArmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Release", DbType="Int NOT NULL")]
		public int Release
		{
			get
			{
				return this._Release;
			}
			set
			{
				if ((this._Release != value))
				{
					this.OnReleaseChanging(value);
					this.SendPropertyChanging();
					this._Release = value;
					this.SendPropertyChanged("Release");
					this.OnReleaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteRunning", DbType="Int NOT NULL")]
		public int RouteRunning
		{
			get
			{
				return this._RouteRunning;
			}
			set
			{
				if ((this._RouteRunning != value))
				{
					this.OnRouteRunningChanging(value);
					this.SendPropertyChanging();
					this._RouteRunning = value;
					this.SendPropertyChanged("RouteRunning");
					this.OnRouteRunningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatchInTraffic", DbType="Int NOT NULL")]
		public int CatchInTraffic
		{
			get
			{
				return this._CatchInTraffic;
			}
			set
			{
				if ((this._CatchInTraffic != value))
				{
					this.OnCatchInTrafficChanging(value);
					this.SendPropertyChanging();
					this._CatchInTraffic = value;
					this.SendPropertyChanged("CatchInTraffic");
					this.OnCatchInTrafficChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpectacularCatch", DbType="Int NOT NULL")]
		public int SpectacularCatch
		{
			get
			{
				return this._SpectacularCatch;
			}
			set
			{
				if ((this._SpectacularCatch != value))
				{
					this.OnSpectacularCatchChanging(value);
					this.SendPropertyChanging();
					this._SpectacularCatch = value;
					this.SendPropertyChanged("SpectacularCatch");
					this.OnSpectacularCatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunBlock", DbType="Int NOT NULL")]
		public int RunBlock
		{
			get
			{
				return this._RunBlock;
			}
			set
			{
				if ((this._RunBlock != value))
				{
					this.OnRunBlockChanging(value);
					this.SendPropertyChanging();
					this._RunBlock = value;
					this.SendPropertyChanged("RunBlock");
					this.OnRunBlockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassBlock", DbType="Int NOT NULL")]
		public int PassBlock
		{
			get
			{
				return this._PassBlock;
			}
			set
			{
				if ((this._PassBlock != value))
				{
					this.OnPassBlockChanging(value);
					this.SendPropertyChanging();
					this._PassBlock = value;
					this.SendPropertyChanged("PassBlock");
					this.OnPassBlockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpactBlock", DbType="Int NOT NULL")]
		public int ImpactBlock
		{
			get
			{
				return this._ImpactBlock;
			}
			set
			{
				if ((this._ImpactBlock != value))
				{
					this.OnImpactBlockChanging(value);
					this.SendPropertyChanging();
					this._ImpactBlock = value;
					this.SendPropertyChanged("ImpactBlock");
					this.OnImpactBlockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tackle", DbType="Int NOT NULL")]
		public int Tackle
		{
			get
			{
				return this._Tackle;
			}
			set
			{
				if ((this._Tackle != value))
				{
					this.OnTackleChanging(value);
					this.SendPropertyChanging();
					this._Tackle = value;
					this.SendPropertyChanged("Tackle");
					this.OnTackleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HitPower", DbType="Int NOT NULL")]
		public int HitPower
		{
			get
			{
				return this._HitPower;
			}
			set
			{
				if ((this._HitPower != value))
				{
					this.OnHitPowerChanging(value);
					this.SendPropertyChanging();
					this._HitPower = value;
					this.SendPropertyChanged("HitPower");
					this.OnHitPowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlayRecognition", DbType="Int NOT NULL")]
		public int PlayRecognition
		{
			get
			{
				return this._PlayRecognition;
			}
			set
			{
				if ((this._PlayRecognition != value))
				{
					this.OnPlayRecognitionChanging(value);
					this.SendPropertyChanging();
					this._PlayRecognition = value;
					this.SendPropertyChanged("PlayRecognition");
					this.OnPlayRecognitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pursuit", DbType="Int NOT NULL")]
		public int Pursuit
		{
			get
			{
				return this._Pursuit;
			}
			set
			{
				if ((this._Pursuit != value))
				{
					this.OnPursuitChanging(value);
					this.SendPropertyChanging();
					this._Pursuit = value;
					this.SendPropertyChanged("Pursuit");
					this.OnPursuitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockShed", DbType="Int NOT NULL")]
		public int BlockShed
		{
			get
			{
				return this._BlockShed;
			}
			set
			{
				if ((this._BlockShed != value))
				{
					this.OnBlockShedChanging(value);
					this.SendPropertyChanging();
					this._BlockShed = value;
					this.SendPropertyChanged("BlockShed");
					this.OnBlockShedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PowerMoves", DbType="Int NOT NULL")]
		public int PowerMoves
		{
			get
			{
				return this._PowerMoves;
			}
			set
			{
				if ((this._PowerMoves != value))
				{
					this.OnPowerMovesChanging(value);
					this.SendPropertyChanging();
					this._PowerMoves = value;
					this.SendPropertyChanged("PowerMoves");
					this.OnPowerMovesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinesseMoves", DbType="Int NOT NULL")]
		public int FinesseMoves
		{
			get
			{
				return this._FinesseMoves;
			}
			set
			{
				if ((this._FinesseMoves != value))
				{
					this.OnFinesseMovesChanging(value);
					this.SendPropertyChanging();
					this._FinesseMoves = value;
					this.SendPropertyChanged("FinesseMoves");
					this.OnFinesseMovesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManCover", DbType="Int NOT NULL")]
		public int ManCover
		{
			get
			{
				return this._ManCover;
			}
			set
			{
				if ((this._ManCover != value))
				{
					this.OnManCoverChanging(value);
					this.SendPropertyChanging();
					this._ManCover = value;
					this.SendPropertyChanged("ManCover");
					this.OnManCoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneCover", DbType="Int NOT NULL")]
		public int ZoneCover
		{
			get
			{
				return this._ZoneCover;
			}
			set
			{
				if ((this._ZoneCover != value))
				{
					this.OnZoneCoverChanging(value);
					this.SendPropertyChanging();
					this._ZoneCover = value;
					this.SendPropertyChanged("ZoneCover");
					this.OnZoneCoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PressCover", DbType="Int NOT NULL")]
		public int PressCover
		{
			get
			{
				return this._PressCover;
			}
			set
			{
				if ((this._PressCover != value))
				{
					this.OnPressCoverChanging(value);
					this.SendPropertyChanging();
					this._PressCover = value;
					this.SendPropertyChanged("PressCover");
					this.OnPressCoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KickPower", DbType="Int NOT NULL")]
		public int KickPower
		{
			get
			{
				return this._KickPower;
			}
			set
			{
				if ((this._KickPower != value))
				{
					this.OnKickPowerChanging(value);
					this.SendPropertyChanging();
					this._KickPower = value;
					this.SendPropertyChanged("KickPower");
					this.OnKickPowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KickAccuracy", DbType="Int NOT NULL")]
		public int KickAccuracy
		{
			get
			{
				return this._KickAccuracy;
			}
			set
			{
				if ((this._KickAccuracy != value))
				{
					this.OnKickAccuracyChanging(value);
					this.SendPropertyChanging();
					this._KickAccuracy = value;
					this.SendPropertyChanged("KickAccuracy");
					this.OnKickAccuracyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_ALL_Predictable", DbType="Int NOT NULL")]
		public int Trait_ALL_Predictable
		{
			get
			{
				return this._Trait_ALL_Predictable;
			}
			set
			{
				if ((this._Trait_ALL_Predictable != value))
				{
					this.OnTrait_ALL_PredictableChanging(value);
					this.SendPropertyChanging();
					this._Trait_ALL_Predictable = value;
					this.SendPropertyChanged("Trait_ALL_Predictable");
					this.OnTrait_ALL_PredictableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_ALL_Clutch", DbType="Int NOT NULL")]
		public int Trait_ALL_Clutch
		{
			get
			{
				return this._Trait_ALL_Clutch;
			}
			set
			{
				if ((this._Trait_ALL_Clutch != value))
				{
					this.OnTrait_ALL_ClutchChanging(value);
					this.SendPropertyChanging();
					this._Trait_ALL_Clutch = value;
					this.SendPropertyChanged("Trait_ALL_Clutch");
					this.OnTrait_ALL_ClutchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_ALL_Penalty", DbType="Int NOT NULL")]
		public int Trait_ALL_Penalty
		{
			get
			{
				return this._Trait_ALL_Penalty;
			}
			set
			{
				if ((this._Trait_ALL_Penalty != value))
				{
					this.OnTrait_ALL_PenaltyChanging(value);
					this.SendPropertyChanging();
					this._Trait_ALL_Penalty = value;
					this.SendPropertyChanged("Trait_ALL_Penalty");
					this.OnTrait_ALL_PenaltyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_OFF_CoverBall", DbType="Int NOT NULL")]
		public int Trait_OFF_CoverBall
		{
			get
			{
				return this._Trait_OFF_CoverBall;
			}
			set
			{
				if ((this._Trait_OFF_CoverBall != value))
				{
					this.OnTrait_OFF_CoverBallChanging(value);
					this.SendPropertyChanging();
					this._Trait_OFF_CoverBall = value;
					this.SendPropertyChanged("Trait_OFF_CoverBall");
					this.OnTrait_OFF_CoverBallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_OFF_FightForYards", DbType="Int NOT NULL")]
		public int Trait_OFF_FightForYards
		{
			get
			{
				return this._Trait_OFF_FightForYards;
			}
			set
			{
				if ((this._Trait_OFF_FightForYards != value))
				{
					this.OnTrait_OFF_FightForYardsChanging(value);
					this.SendPropertyChanging();
					this._Trait_OFF_FightForYards = value;
					this.SendPropertyChanged("Trait_OFF_FightForYards");
					this.OnTrait_OFF_FightForYardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_OFF_DropOpenPasses", DbType="Int NOT NULL")]
		public int Trait_OFF_DropOpenPasses
		{
			get
			{
				return this._Trait_OFF_DropOpenPasses;
			}
			set
			{
				if ((this._Trait_OFF_DropOpenPasses != value))
				{
					this.OnTrait_OFF_DropOpenPassesChanging(value);
					this.SendPropertyChanging();
					this._Trait_OFF_DropOpenPasses = value;
					this.SendPropertyChanged("Trait_OFF_DropOpenPasses");
					this.OnTrait_OFF_DropOpenPassesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_OFF_FeetInBounds", DbType="Int NOT NULL")]
		public int Trait_OFF_FeetInBounds
		{
			get
			{
				return this._Trait_OFF_FeetInBounds;
			}
			set
			{
				if ((this._Trait_OFF_FeetInBounds != value))
				{
					this.OnTrait_OFF_FeetInBoundsChanging(value);
					this.SendPropertyChanging();
					this._Trait_OFF_FeetInBounds = value;
					this.SendPropertyChanged("Trait_OFF_FeetInBounds");
					this.OnTrait_OFF_FeetInBoundsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_OFF_PossesionCatch", DbType="Int NOT NULL")]
		public int Trait_OFF_PossesionCatch
		{
			get
			{
				return this._Trait_OFF_PossesionCatch;
			}
			set
			{
				if ((this._Trait_OFF_PossesionCatch != value))
				{
					this.OnTrait_OFF_PossesionCatchChanging(value);
					this.SendPropertyChanging();
					this._Trait_OFF_PossesionCatch = value;
					this.SendPropertyChanged("Trait_OFF_PossesionCatch");
					this.OnTrait_OFF_PossesionCatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_OFF_AggressiveCatch", DbType="Int NOT NULL")]
		public int Trait_OFF_AggressiveCatch
		{
			get
			{
				return this._Trait_OFF_AggressiveCatch;
			}
			set
			{
				if ((this._Trait_OFF_AggressiveCatch != value))
				{
					this.OnTrait_OFF_AggressiveCatchChanging(value);
					this.SendPropertyChanging();
					this._Trait_OFF_AggressiveCatch = value;
					this.SendPropertyChanged("Trait_OFF_AggressiveCatch");
					this.OnTrait_OFF_AggressiveCatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_OFF_CatchOnTheRun", DbType="Int NOT NULL")]
		public int Trait_OFF_CatchOnTheRun
		{
			get
			{
				return this._Trait_OFF_CatchOnTheRun;
			}
			set
			{
				if ((this._Trait_OFF_CatchOnTheRun != value))
				{
					this.OnTrait_OFF_CatchOnTheRunChanging(value);
					this.SendPropertyChanging();
					this._Trait_OFF_CatchOnTheRun = value;
					this.SendPropertyChanged("Trait_OFF_CatchOnTheRun");
					this.OnTrait_OFF_CatchOnTheRunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_QB_ThrowBallAway", DbType="Int NOT NULL")]
		public int Trait_QB_ThrowBallAway
		{
			get
			{
				return this._Trait_QB_ThrowBallAway;
			}
			set
			{
				if ((this._Trait_QB_ThrowBallAway != value))
				{
					this.OnTrait_QB_ThrowBallAwayChanging(value);
					this.SendPropertyChanging();
					this._Trait_QB_ThrowBallAway = value;
					this.SendPropertyChanged("Trait_QB_ThrowBallAway");
					this.OnTrait_QB_ThrowBallAwayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_QB_SensePressure", DbType="Int NOT NULL")]
		public int Trait_QB_SensePressure
		{
			get
			{
				return this._Trait_QB_SensePressure;
			}
			set
			{
				if ((this._Trait_QB_SensePressure != value))
				{
					this.OnTrait_QB_SensePressureChanging(value);
					this.SendPropertyChanging();
					this._Trait_QB_SensePressure = value;
					this.SendPropertyChanged("Trait_QB_SensePressure");
					this.OnTrait_QB_SensePressureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_QB_TightSpiral", DbType="Int NOT NULL")]
		public int Trait_QB_TightSpiral
		{
			get
			{
				return this._Trait_QB_TightSpiral;
			}
			set
			{
				if ((this._Trait_QB_TightSpiral != value))
				{
					this.OnTrait_QB_TightSpiralChanging(value);
					this.SendPropertyChanging();
					this._Trait_QB_TightSpiral = value;
					this.SendPropertyChanged("Trait_QB_TightSpiral");
					this.OnTrait_QB_TightSpiralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_QB_Style", DbType="Int NOT NULL")]
		public int Trait_QB_Style
		{
			get
			{
				return this._Trait_QB_Style;
			}
			set
			{
				if ((this._Trait_QB_Style != value))
				{
					this.OnTrait_QB_StyleChanging(value);
					this.SendPropertyChanging();
					this._Trait_QB_Style = value;
					this.SendPropertyChanged("Trait_QB_Style");
					this.OnTrait_QB_StyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_QB_ForcePass", DbType="Int NOT NULL")]
		public int Trait_QB_ForcePass
		{
			get
			{
				return this._Trait_QB_ForcePass;
			}
			set
			{
				if ((this._Trait_QB_ForcePass != value))
				{
					this.OnTrait_QB_ForcePassChanging(value);
					this.SendPropertyChanging();
					this._Trait_QB_ForcePass = value;
					this.SendPropertyChanged("Trait_QB_ForcePass");
					this.OnTrait_QB_ForcePassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_DEF_BullRush", DbType="Int NOT NULL")]
		public int Trait_DEF_BullRush
		{
			get
			{
				return this._Trait_DEF_BullRush;
			}
			set
			{
				if ((this._Trait_DEF_BullRush != value))
				{
					this.OnTrait_DEF_BullRushChanging(value);
					this.SendPropertyChanging();
					this._Trait_DEF_BullRush = value;
					this.SendPropertyChanged("Trait_DEF_BullRush");
					this.OnTrait_DEF_BullRushChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_DEF_SwimMove", DbType="Int NOT NULL")]
		public int Trait_DEF_SwimMove
		{
			get
			{
				return this._Trait_DEF_SwimMove;
			}
			set
			{
				if ((this._Trait_DEF_SwimMove != value))
				{
					this.OnTrait_DEF_SwimMoveChanging(value);
					this.SendPropertyChanging();
					this._Trait_DEF_SwimMove = value;
					this.SendPropertyChanged("Trait_DEF_SwimMove");
					this.OnTrait_DEF_SwimMoveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_DEF_SpinMove", DbType="Int NOT NULL")]
		public int Trait_DEF_SpinMove
		{
			get
			{
				return this._Trait_DEF_SpinMove;
			}
			set
			{
				if ((this._Trait_DEF_SpinMove != value))
				{
					this.OnTrait_DEF_SpinMoveChanging(value);
					this.SendPropertyChanging();
					this._Trait_DEF_SpinMove = value;
					this.SendPropertyChanged("Trait_DEF_SpinMove");
					this.OnTrait_DEF_SpinMoveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_DEF_HighMotor", DbType="Int NOT NULL")]
		public int Trait_DEF_HighMotor
		{
			get
			{
				return this._Trait_DEF_HighMotor;
			}
			set
			{
				if ((this._Trait_DEF_HighMotor != value))
				{
					this.OnTrait_DEF_HighMotorChanging(value);
					this.SendPropertyChanging();
					this._Trait_DEF_HighMotor = value;
					this.SendPropertyChanged("Trait_DEF_HighMotor");
					this.OnTrait_DEF_HighMotorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_DEF_BigHitter", DbType="Int NOT NULL")]
		public int Trait_DEF_BigHitter
		{
			get
			{
				return this._Trait_DEF_BigHitter;
			}
			set
			{
				if ((this._Trait_DEF_BigHitter != value))
				{
					this.OnTrait_DEF_BigHitterChanging(value);
					this.SendPropertyChanging();
					this._Trait_DEF_BigHitter = value;
					this.SendPropertyChanged("Trait_DEF_BigHitter");
					this.OnTrait_DEF_BigHitterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_DEF_StripBall", DbType="Int NOT NULL")]
		public int Trait_DEF_StripBall
		{
			get
			{
				return this._Trait_DEF_StripBall;
			}
			set
			{
				if ((this._Trait_DEF_StripBall != value))
				{
					this.OnTrait_DEF_StripBallChanging(value);
					this.SendPropertyChanging();
					this._Trait_DEF_StripBall = value;
					this.SendPropertyChanged("Trait_DEF_StripBall");
					this.OnTrait_DEF_StripBallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trait_DEF_PlayBall", DbType="Int NOT NULL")]
		public int Trait_DEF_PlayBall
		{
			get
			{
				return this._Trait_DEF_PlayBall;
			}
			set
			{
				if ((this._Trait_DEF_PlayBall != value))
				{
					this.OnTrait_DEF_PlayBallChanging(value);
					this.SendPropertyChanging();
					this._Trait_DEF_PlayBall = value;
					this.SendPropertyChanged("Trait_DEF_PlayBall");
					this.OnTrait_DEF_PlayBallChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
